POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
"name": "Andres Muli",
"number": "61-32-9153122"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3001/api/persons/